import chalkTemplate from 'chalk-template';
import { existsSync, writeFileSync } from 'fs';
import { basename, resolve } from 'path';
import { getWasiSdkDir, WASI_SDK_VERSION } from './wasiSdk.js';

export interface ChipMakefileOptions {
  quiet?: boolean;
  output?: string;
  chipName?: string;
}

const WOKWI_API_HEADER_URL = 'https://wokwi.com/api/chips/wokwi-api.h';

function generateMakefile(sourceFiles: string[], chipName: string): string {
  const sources = sourceFiles.length > 0 ? sourceFiles.join(' ') : 'main.c';

  return `# Wokwi Custom Chip Makefile
# Generated by wokwi-cli
#
# Usage:
#   make          - Build the chip
#   make clean    - Remove build artifacts
#   make wokwi-api.h - Download the Wokwi API header
#
# Requirements:
#   - WASI-SDK (https://github.com/WebAssembly/wasi-sdk)
#   - Set WASI_SDK_PATH environment variable or install to ~/.wokwi/wasi-sdk
#

# Configuration
CHIP_NAME ?= ${chipName}
SOURCES ?= ${sources}
OUTPUT ?= $(CHIP_NAME).wasm

# WASI-SDK paths
WASI_SDK_PATH ?= ${getWasiSdkDir()}
WASI_SDK_VERSION ?= ${WASI_SDK_VERSION}

# Compiler settings
CC = $(WASI_SDK_PATH)/bin/clang
SYSROOT = $(WASI_SDK_PATH)/share/wasi-sysroot

# Compilation flags
CFLAGS = --target=wasm32-wasi \\
         --sysroot=$(SYSROOT) \\
         -nostartfiles \\
         -I. \\
         -O2

LDFLAGS = -Wl,--no-entry \\
          -Wl,--import-memory \\
          -Wl,--export-table

# Default target
all: check-sdk wokwi-api.h $(OUTPUT)

# Build the WASM file
$(OUTPUT): $(SOURCES) wokwi-api.h
	@echo "Compiling $(CHIP_NAME)..."
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(SOURCES)
	@echo "Success! Output: $@ ($$(du -h $@ | cut -f1))"

# Check WASI-SDK is available
check-sdk:
	@if [ ! -d "$(WASI_SDK_PATH)" ]; then \\
		echo "Error: WASI-SDK not found at $(WASI_SDK_PATH)"; \\
		echo ""; \\
		echo "Install WASI-SDK:"; \\
		echo "  Option 1: Run 'wokwi-cli chip compile' once to auto-install"; \\
		echo "  Option 2: Download from https://github.com/WebAssembly/wasi-sdk/releases"; \\
		echo "  Option 3: Set WASI_SDK_PATH environment variable"; \\
		exit 1; \\
	fi

# Download wokwi-api.h if not present
wokwi-api.h:
	@if [ ! -f wokwi-api.h ]; then \\
		echo "Downloading wokwi-api.h..."; \\
		curl -sL "${WOKWI_API_HEADER_URL}" -o wokwi-api.h; \\
		echo "Downloaded wokwi-api.h"; \\
	fi

# Clean build artifacts
clean:
	rm -f $(OUTPUT)

# Clean everything including downloaded files
distclean: clean
	rm -f wokwi-api.h

.PHONY: all check-sdk clean distclean
`;
}

export async function chipMakefile(
  sourceFiles: string[],
  options: ChipMakefileOptions = {},
): Promise<void> {
  const { quiet = false, output = 'Makefile', chipName } = options;

  const outputPath = resolve(output);

  // Determine chip name
  let resolvedChipName = chipName;
  if (!resolvedChipName) {
    if (sourceFiles.length > 0) {
      resolvedChipName = basename(sourceFiles[0]).replace(/\.(c|cpp|cc|cxx)$/i, '');
    } else {
      resolvedChipName = 'chip';
    }
  }

  // Check if Makefile already exists
  if (existsSync(outputPath)) {
    if (!quiet) {
      console.log(chalkTemplate`{yellow Warning:} ${output} already exists, overwriting...`);
    }
  }

  if (!quiet) {
    console.log(chalkTemplate`{bold Generating Makefile...}`);
    console.log();
  }

  const makefileContent = generateMakefile(sourceFiles, resolvedChipName);
  writeFileSync(outputPath, makefileContent);

  console.log(chalkTemplate`{green Success!} Generated {cyan ${outputPath}}`);
  console.log();
  console.log(chalkTemplate`{bold Usage:}`);
  console.log(chalkTemplate`  {dim $} make              {dim # Build the chip}`);
  console.log(chalkTemplate`  {dim $} make clean        {dim # Remove build artifacts}`);
  console.log(chalkTemplate`  {dim $} make wokwi-api.h  {dim # Download API header}`);

  if (!process.env.WASI_SDK_PATH && !existsSync(getWasiSdkDir())) {
    console.log();
    console.log(chalkTemplate`{yellow Note:} WASI-SDK not found.`);
    console.log(chalkTemplate`  Run {green wokwi-cli chip compile <source>} once to auto-install,`);
    console.log(chalkTemplate`  or set {yellow WASI_SDK_PATH} environment variable.`);
  }
}
